Section-rosly
kotikm81/training-codehunters-team-proj pull request #2
Opened 2021-03-28 11:07 UTC by AlexRosly

2021-03-28 17:53 UTC, kotikm81 requested changes

2021-03-28 17:53 UTC, kotikm81 commented on src/partials/example.html
> -<article class="example">
Не правильно сделал. Не нужно трогать страницу example.html. Создай свою, и в ней только секцию. Это фрагмент кода, а не страница целиком. Без  <head>, <body> и т.д.. Посмотри как в примере  example.html. А в файл index.html нужно потом вставить <include> с сылкой на свой фрагмент.

2021-03-28 17:53 UTC, kotikm81 commented on src/sass/main.scss
> +@import './section';
тут ты не удаляешь example, а добавляешь свой фрагмент

2021-03-29 17:47 UTC, AlexRosly commented on src/partials/example.html
> -<article class="example">
Исправил

2021-03-29 17:47 UTC, AlexRosly commented on src/sass/main.scss
> +@import './section';
Исправил

2021-03-29 18:20 UTC, kotikm81 approved these changes

2021-03-29 18:20 UTC, merged